version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "harunonsystem"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
