name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true

jobs:
  test-matrix:
    name: Quality Checks
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [ "24.x" ]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: ./.github/actions

      - name: Run format check
        run: bun run format:check

      - name: Run lint check
        run: bun run lint

      - name: Run type check
        run: bun run typecheck

      - name: Run tests
        run: bun run test

      
